### ISSUE TITLE
Deprecation notice using Doctrine\Common\Lexer\Token properties via ArrayAccess

### ISSUE THREAD

**Issue by josephLaurent** [coduo/php-matcher#475]
Hello,

I have some deprecation notice using `Coduo\PHPMatcher\PHPUnit\PHPMatcherAssertions::matchesPattern` function because `Coduo\PHPMatcher\Parser` is using deprecated array access on a `Coduo\PHPMatcher\Lexer` object.

I have exactly this error:
```
Indirect deprecation triggered by App\Tests\Functional\Controller\Campaign\Cost\GetControllerTest::testCanDenyAccess:
Accessing Doctrine\Common\Lexer\Token properties via ArrayAccess is deprecated, use the value, type or position property instead (Token.php:68 called by Parser.php:266, https://github.com/doctrine/lexer/pull/79, package doctrine/lexer)
Stack trace:
#0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(16384, 'Accessing Doctr...', '/srv/app/vendor...', 210)
#1 vendor/doctrine/lexer/src/Token.php(68): Doctrine\Deprecations\Deprecation::trigger('doctrine/lexer', 'https://github....', 'Accessing Doctr...', 'Doctrine\\Common...')
#2 vendor/coduo/php-matcher/src/Parser.php(266): Doctrine\Common\Lexer\Token->offsetExists('position')
#3 vendor/coduo/php-matcher/src/Parser.php(72): Coduo\PHPMatcher\Parser->unexpectedSyntaxError(Object(Doctrine\Common\Lexer\Token), '@type@ pattern')
#4 vendor/coduo/php-matcher/src/Parser.php(60): Coduo\PHPMatcher\Parser->getPattern()
#5 vendor/coduo/php-matcher/src/Parser.php(32): Coduo\PHPMatcher\Parser->getAST('{"error":"Acces...')
...
```

It's seem really easy to fix and I can try to do it if it help ?
Thank you in advance for your help :)

**Comment by norberttech** [comment]
resolved by https://github.com/coduo/php-matcher/pull/477
